// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleMcRecords.Data;

#nullable disable

namespace SimpleMcRecords.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230817201523_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("SimpleMcRecords.Models.Advancement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Advancements");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.PlayerAdvancement", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdvancementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId", "AdvancementId");

                    b.HasIndex("AdvancementId");

                    b.ToTable("PlayerAdvancements");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.Advancement", b =>
                {
                    b.HasOne("SimpleMcRecords.Models.Category", "Category")
                        .WithMany("Advancements")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.PlayerAdvancement", b =>
                {
                    b.HasOne("SimpleMcRecords.Models.Advancement", "Advancement")
                        .WithMany("PlayerAdvancements")
                        .HasForeignKey("AdvancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleMcRecords.Models.Player", "Player")
                        .WithMany("PlayerAdvancements")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advancement");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.Score", b =>
                {
                    b.HasOne("SimpleMcRecords.Models.Player", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.Advancement", b =>
                {
                    b.Navigation("PlayerAdvancements");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.Category", b =>
                {
                    b.Navigation("Advancements");
                });

            modelBuilder.Entity("SimpleMcRecords.Models.Player", b =>
                {
                    b.Navigation("PlayerAdvancements");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
